### ISSUE TITLE
I had some problems with your example data

### ISSUE THREAD

**Issue by Y0NEKO** [mckennalab/SingleCellLineage#1]
I tried to run the script with basic_example.txt file but the graph is blank, I think maybe it's because the barcode.fq file is NA in this file. And I also tried your 10X_example data, but it will report an error at step 4 and stop:
`java.util.NoSuchElementException: key not found: CCGGACTCAGATCTCGAGCTCAAGCT`
then I found the crispr_tearsheet.txt in the 10X_example folder had different data format with the basic_example.txt,  I'm a little confused about the meaning of fastq1, fastq2 and barcode.fastq1, barcode.fastq2, could you explain it in more detail?

**Comment by aaronmck** [comment]
Hi YONEKO,

I've updated the example data and the docker container. The code and the 10X example hadn't tracked each other, but it should be fixed now.

-Aaron

**Comment by aaronmck** [comment]
I'll close this for now, if I didn't solve the issue please come back and open the issue back up. Thanks!
